name: terraform

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: init
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{secrets.SSH_KEY_GITHUB_ACTIONS}}'
          terraform init
      - name: fmt
        run: terraform fmt
      - name: validate 
        run: terraform validate
      - name: plan
        run: terraform plan
